# Generated by Django 3.2.7 on 2021-10-06 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_orderplaced'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Andman & Nicobar Island', 'Andman & Nicobar Island'), ('Bihar', 'Bihar'), ('Goa', 'Goa'), ('Asam', 'Asam'), ('Mijoram', 'Mijoram'), ('Andhrapradesh', 'Andhrapradesh'), ('Telangna', 'Telangna'), ('Chhatisgadh', 'Chhatisgadh'), ('maharastra', 'maharastra'), ('Jharkhand', 'Jharkhand')], max_length=50),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Delevered', 'Accepted'), ('Packed', 'Packed'), ('On the way', 'On the way'), ('Delivered', 'Delivered'), ('Cancel', 'Cancel')], default='pending', max_length=50),
        ),
    ]
